require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AirplanesController do

  # This should return the minimal set of attributes required to create a valid
  # Airplane. As you add validations to Airplane, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "valid", "rows" => "10", "columns" => "10" } }
  let(:unvalid_attributes) { { "name" => "unvalid", "rows" => nil, "columns" => "10" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AirplanesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all airplanes as @airplanes" do
      airplane = Airplane.create! valid_attributes
      get :index, {}, valid_session
      assigns(:airplanes).should eq([airplane])
    end
  end

  describe "GET show" do
    it "assigns the requested airplane as @airplane" do
      airplane = Airplane.create! valid_attributes
      get :show, {:id => airplane.to_param}, valid_session
      assigns(:airplane).should eq(airplane)
    end
  end

  describe "GET new" do
    it "assigns a new airplane as @airplane" do
      get :new, {}, valid_session
      assigns(:airplane).should be_a_new(Airplane)
    end
  end

  describe "GET edit" do
    it "assigns the requested airplane as @airplane" do
      airplane = Airplane.create! valid_attributes
      get :edit, {:id => airplane.to_param}, valid_session
      assigns(:airplane).should eq(airplane)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Airplane" do
        expect {
          post :create, {:airplane => valid_attributes }, valid_session
        }.to change(Airplane, :count).by(1)
      end

      it "assigns a newly created airplane as @airplane" do
        post :create, {:airplane => valid_attributes }, valid_session
        assigns(:airplane).should be_a(Airplane)
        assigns(:airplane).should be_persisted
      end

      it "redirects to the created airplane" do
        post :create, {:airplane => valid_attributes }, valid_session
        response.should redirect_to(Airplane.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved airplane as @airplane" do
        # Trigger the behavior that occurs when invalid params are submitted
        Airplane.any_instance.stub(:save).and_return(false)
        post :create, {:airplane => unvalid_attributes }, valid_session
        assigns(:airplane).should be_a_new(Airplane)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Airplane.any_instance.stub(:save).and_return(false)
        post :create, {:airplane => unvalid_attributes }, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested airplane" do
        airplane = Airplane.create! valid_attributes
        # Assuming there are no other airplanes in the database, this
        # specifies that the Airplane created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Airplane.any_instance.should_receive(:update).with(valid_attributes)
        put :update, {:id => airplane.to_param, :airplane => valid_attributes }, valid_session
      end

      it "assigns the requested airplane as @airplane" do
        airplane = Airplane.create! valid_attributes
        put :update, {:id => airplane.to_param, :airplane => valid_attributes }, valid_session
        assigns(:airplane).should eq(airplane)
      end

      it "redirects to the airplane" do
        airplane = Airplane.create! valid_attributes
        put :update, {:id => airplane.to_param, :airplane => valid_attributes }, valid_session
        response.should redirect_to(airplane)
      end
    end

    describe "with invalid params" do
      it "assigns the airplane as @airplane" do
        airplane = Airplane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Airplane.any_instance.stub(:save).and_return(false)
        put :update, {:id => airplane.to_param, :airplane => unvalid_attributes }, valid_session
        assigns(:airplane).should eq(airplane)
      end

      it "re-renders the 'edit' template" do
        airplane = Airplane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Airplane.any_instance.stub(:save).and_return(false)
        put :update, {:id => airplane.to_param, :airplane => unvalid_attributes }, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested airplane" do
      airplane = Airplane.create! valid_attributes
      expect {
        delete :destroy, {:id => airplane.to_param }, valid_session
      }.to change(Airplane, :count).by(-1)
    end

    it "redirects to the airplanes list" do
      airplane = Airplane.create! valid_attributes
      delete :destroy, {:id => airplane.to_param }, valid_session
      response.should redirect_to(airplanes_url)
    end
  end

end
