require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FlightsController do

  # This should return the minimal set of attributes required to create a valid
  # Flight. As you add validations to Flight, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => 10 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlightsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all flights as @flights" do
      flight = Flight.create! valid_attributes
      get :index, {}, valid_session
      assigns(:flights).should eq([flight])
    end
  end

  describe "GET show" do
    it "assigns the requested flight as @flight" do
      flight = Flight.create! valid_attributes
      get :show, {:id => flight.to_param}, valid_session
      assigns(:flight).should eq(flight)
    end
  end

  describe "GET new" do
    it "assigns a new flight as @flight" do
      get :new, {}, valid_session
      assigns(:flight).should be_a_new(Flight)
    end
  end

  describe "GET edit" do
    it "assigns the requested flight as @flight" do
      flight = Flight.create! valid_attributes
      get :edit, {:id => flight.to_param}, valid_session
      assigns(:flight).should eq(flight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Flight" do
        expect {
          post :create, {:flight => valid_attributes}, valid_session
        }.to change(Flight, :count).by(1)
      end

      it "assigns a newly created flight as @flight" do
        post :create, {:flight => valid_attributes}, valid_session
        assigns(:flight).should be_a(Flight)
        assigns(:flight).should be_persisted
      end

      it "redirects to the created flight" do
        post :create, {:flight => valid_attributes}, valid_session
        response.should redirect_to(Flight.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved flight as @flight" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flight.any_instance.stub(:save).and_return(false)
        post :create, {:flight => { "number" => nil }}, valid_session
        assigns(:flight).should be_a_new(Flight)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flight.any_instance.stub(:save).and_return(false)
        post :create, {:flight => { "number" => nil }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested flight" do
        flight = Flight.create! valid_attributes
        # Assuming there are no other flights in the database, this
        # specifies that the Flight created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Flight.any_instance.should_receive(:update).with({ "number" => "10" })
        put :update, {:id => flight.to_param, :flight => { "number" => "10" }}, valid_session
      end

      it "assigns the requested flight as @flight" do
        flight = Flight.create! valid_attributes
        put :update, {:id => flight.to_param, :flight => valid_attributes}, valid_session
        assigns(:flight).should eq(flight)
      end

      it "redirects to the flight" do
        flight = Flight.create! valid_attributes
        put :update, {:id => flight.to_param, :flight => valid_attributes}, valid_session
        response.should redirect_to(flight)
      end
    end

    describe "with invalid params" do
      it "assigns the flight as @flight" do
        flight = Flight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flight.any_instance.stub(:save).and_return(false)
        put :update, {:id => flight.to_param, :flight => { "number" => "invalid value" }}, valid_session
        assigns(:flight).should eq(flight)
      end

      it "re-renders the 'edit' template" do
        flight = Flight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flight.any_instance.stub(:save).and_return(false)
        put :update, {:id => flight.to_param, :flight => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested flight" do
      flight = Flight.create! valid_attributes
      expect {
        delete :destroy, {:id => flight.to_param}, valid_session
      }.to change(Flight, :count).by(-1)
    end

    it "redirects to the flights list" do
      flight = Flight.create! valid_attributes
      delete :destroy, {:id => flight.to_param}, valid_session
      response.should redirect_to(flights_url)
    end
  end

end
